name: C/C++ CI

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: exec
      run: ./test
    - name: pwd
      run: pwd && echo && ls
    - name: release
      id: release
      uses: actions/upload-artifact@v2
      with:
        name: releaseidk
        path: /home/runner/work/ci/ci/test
