name: C/C++ CI

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  macOS:
    runs-on: macos-11
    steps:
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make test
      run: make test
