name: C/C++ CI

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  macOS:
    runs-on: macos-11
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'true'
        fetch-depth: 0
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make test
      run: make test
