name: C/C++ CI

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  macOS:
    runs-on: macos-11
    steps:
    - name: macOS Build
      id: macOS-Build
      run:
        make
  
