name: C/C++ CI

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  build-macOS-ARM64:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: arch -arm64 make
    - name: exec
      run: ./test
    - name: envdetails
      run: ls && echo && pwd
    - name: release
      id: release
      uses: actions/upload-artifact@v2
      with:
        name: release-macOS-ARM64
        path: /Users/runner/work/ci/ci/test

  build-macOS-x86_64:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: exec
      run: ./test
    - name: envdetails
      run: ls && echo && pwd
    - name: release
      id: release
      uses: actions/upload-artifact@v2
      with:
        name: release-macOS-x86_64
        path: /Users/runner/work/ci/ci/test
    
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: exec
      run: ./test
    - name: release
      id: release
      uses: actions/upload-artifact@v2
      with:
        name: release-ubuntu
        path: /home/runner/work/ci/ci/test
